export const categories = [{
    name: 'Bread',
    count: 2,
    subCategories: [],
  },
  {
    name: 'Fruits',
    count: 10,
    subCategories: [{
        name: 'Fresh Nuts',
        count: 1,
      },
      {
        name: 'Millk Cream',
        count: 0,
      },
    ],
  },
  {
    name: 'Meat',
    count: 16,
    subCategories: [],
  },
  {
    name: 'Uncategorized',
    count: 37,
    subCategories: [],
  },
  {
    name: 'Vegetables',
    count: 14,
    subCategories: [],
  },
]

export const shopProducts = [{
    name: 'Wrapped Cabbage',
    id: 0,
    price: '782.92',
    rating: 3,
    sale: '',
    categories: ['Vegetables'],
  },
  {
    name: 'Sweetcorn 4 Pack',
    id: 1,
    price: '220.20',
    rating: 4,
    sale: '',
    categories: ['Vegetables'],
  },
  {
    name: 'Mixed Chillies Pack 150g',
    id: 2,
    price: '546.04',
    rating: 4,
    sale: '-25%',
    categories: ['Vegetables', 'Fruits'],
  },
  {
    name: 'Beef Potjiekos Per kg',
    id: 3,
    price: '535.40',
    rating: 3,
    sale: '',
    categories: ['Meat'],
  },
  {
    name: 'Wrapped Red Cabbage',
    id: 4,
    price: '500.91',
    rating: 4,
    sale: '',
    categories: ['Vegetables'],
  },
  {
    name: 'Farmer’s Choice Chicken Wings',
    id: 5,
    price: '725.47',
    rating: 3,
    sale: '',
    categories: ['Meat'],
  },
  {
    name: 'Packham’s Triumph Pears Bag',
    id: 6,
    price: '323.00',
    rating: 4,
    sale: '-27%',
    categories: ['Fruits'],
  },
  {
    name: 'Frozen Angelfish Per kg',
    id: 7,
    price: '647.32',
    rating: 4,
    sale: '',
    categories: ['Meat'],
  },
  {
    name: 'Steers Tomato Sauce 375ml',
    id: 8,
    price: '91.38',
    rating: 3,
    sale: '',
    categories: ['Vegetables'],
  },
  {
    name: 'Large Queen Pineapple',
    id: 9,
    price: '78.09',
    rating: 3,
    sale: '-48%',
    categories: ['Fruits'],
  },
  {
    name: 'Peppered Mackerel Fillets 200g',
    id: 10,
    price: '14.84',
    rating: 4,
    sale: '',
    categories: ['Meat'],
  },
  {
    name: 'Cut Queen Pumpkin Per kg',
    id: 11,
    price: '910.53',
    rating: 3,
    sale: '',
    categories: ['Fruits'],
  },
  {
    name: 'Smokies Vienna’s Per kg',
    id: 12,
    price: '101.64',
    rating: 3,
    sale: '',
    categories: ['Meat'],
  },
  {
    name: 'Papaya Single',
    id: 13,
    price: '546.04',
    rating: 4,
    sale: '-27%',
    categories: ['Fruits'],
  },
  {
    name: 'White Mushrooms Sliced 250g',
    id: 14,
    price: '161.44',
    rating: 4,
    sale: '',
    categories: ['Vegetables'],
  },
  {
    name: 'Beef Club & T-Bone Per kg',
    id: 15,
    price: '814.96',
    rating: 4,
    sale: '',
    categories: ['Meat'],
  },
  {
    name: 'East Coast Small Sole Fish',
    id: 16,
    price: '168.22',
    rating: 4,
    sale: '',
    categories: ['Vegetables'],
  },
  {
    name: 'Kiwi Fruit Single',
    id: 17,
    price: '100.13',
    rating: 5,
    sale: '',
  },
  {
    name: 'Kale Bunch',
    id: 18,
    price: '391.96',
    rating: 3,
    sale: ''
  },
  {
    name: 'Cara-Cara Oranges Pack 2kg',
    id: 19,
    price: '925.36',
    rating: 4,
    sale: '',
  },
  {
    name: 'Cape Point Fresh 200g',
    id: 20,
    price: '142.12',
    rating: 3,
    sale: '',
  },
  {
    name: 'Thinly Sliced Beef Brisket',
    id: 21,
    price: '985.97',
    rating: 4,
    sale: '',
  },
  {
    name: 'Soup & Stew Mix Pack 1.5kg',
    id: 22,
    price: '323.00',
    rating: 4,
    sale: '-40%',
  },
  {
    name: 'Loose Medium Onions Per kg',
    id: 23,
    price: '216.81',
    rating: 4,
    sale: '',
  },
  {
    name: 'Beef Goulash Per kg',
    id: 24,
    price: '563.72',
    rating: 4,
    sale: '',
  },
  {
    name: 'Pork Pack Per kg',
    id: 25,
    price: '496.64',
    rating: 4,
    sale: '',
  },
  {
    name: 'Pumpkin Cubes 500g',
    id: 26,
    price: '319.83',
    rating: 3,
    sale: '',
  },
  {
    name: 'Equatorial Banana Per kg',
    id: 27,
    price: '693.95',
    rating: 4,
    sale: '',
  },
  {
    name: 'Green Beans 350g',
    id: 28,
    price: '609.73',
    rating: 4,
    sale: '',
  },
  {
    name: 'Extra Large Eggs 6 Pack',
    id: 29,
    price: '723.67',
    rating: 4,
    sale: '',
  },
  {
    name: 'Gourmet Beef Sosaties Per kg',
    id: 30,
    price: '646.97',
    rating: 4,
    sale: '',
  },
  {
    name: 'Frozen Jumbo Hake Fillets',
    id: 31,
    price: '224.76',
    rating: 4,
    sale: '',
  },
]
